### ISSUE TITLE
Dead Docs link in README

### ISSUE THREAD

**Issue by mdaum** [xmppjs/ltx#118]
Is there a new endpoint? Thanks!

**Comment by Druotic** [comment]
Any updates on this? @sonnyp

**Comment by sonnyp** [comment]
Sorry we don't really have doc for ltx even the website didn't have much, I'll tackle this when I'm back from holidays.

If you're looking for xmpp.js documentation http://xmppjs.org/xml/

**Comment by aredridel** [comment]
Ping? I've used ltx a bunch, and what docs were there are better than nothing!
