### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by mogsie** [xmppjs/ltx#120]
Hi!  While working on the entity expansion, I found that the actual entity replacement is done using a regular expression.  I know it's a micro-optimization, but I was able to shave 20% off parsing a typical (15-kilobyteish) document by replacing the regular expression with an indexOf loop.

I can open a PR with the code changes if this is interesting:

``` patch
$ git diff --staged 
diff --git a/lib/escape.js b/lib/escape.js
index 5fd682e..dbf023f 100644
--- a/lib/escape.js
+++ b/lib/escape.js
@@ -46,7 +46,22 @@ exports.escapeXML = function escapeXML (s) {
 }
 
 exports.unescapeXML = function unescapeXML (s) {
-  return s.replace(/&(amp|lt|gt|quot|apos|#x[0-9a-fA-F]+|#[0-9]+);/g, unescapeXMLReplace)
+  var result = ''
+  var start = -1
+  var end = -1
+  var previous = 0
+  while ((start = s.indexOf('&', previous)) !== -1 && (end = s.indexOf(';', start + 1))) {
+    // if (previous != start)
+    result = result +
+      s.substring(previous, start) +
+      unescapeXMLReplace(s.substring(start, end + 1))
+    previous = end + 1
+  }
+
+  // push the remaining characters
+  result = result + s.substring(previous)
+
+  return result
 }
 
 exports.escapeXMLText = function escapeXMLText (s) {
```

I do understand that it increases complexity; but this code, if anything in an XML parser is "hot" code and needs to run fast.

**Comment by mogsie** [comment]
I found another place where similar improvements can be made.  The main ltx parser goes through the document character-by-character looking for certain things with a switch statement.  If you know exactly what you're looking for then dramatic improvements can be had by using native calls to find what you're looking for:

This change to the main ltx parse loop drops the parsing time a few percent (5-6?)  Doing it for attributes did a lot more for me, shaving off another 10% of CPU time.

Essentially this:
- If we'er in STATE_TEXT, move 'pos' forwards from 'pos' to the first instance of the '<' character
- If we're in the STATE_ATTR_VALUE, move 'pos' forwards to the first instance of the closing quote character.

Similar optimizations can be done for 'CDATA` states (look for `]]>`) and probably comments too.

``` patch
     for (; pos < data.length; pos++) {
+      if (state === STATE_TEXT) {
+        var lt = data.indexOf('<', pos)
+        if (lt !== -1 && pos !== lt) {
+          pos = lt
+        }
+      }
+      else if (state === STATE_ATTR_VALUE) {
+        var quot = data.indexOf(attrQuoteChar, pos)
+        if (quot !== -1) {
+          pos = quot
+        }
+      }

```

**Comment by sonnyp** [comment]
@mogsie appreciated, thanks :)

Can you open two pull requests?

**Comment by mogsie** [comment]
Sure thing! \o/

**Comment by mogsie** [comment]
Opened two PRs @sonnyp :)
