### ISSUE TITLE
Uglify Js error on version 2.7.2

### ISSUE THREAD

**Issue by jpablom** [xmppjs/ltx#124]
Hi, im using a library that depends on ltx. When updated to 2.7.2 i started to get an error with gulp-uglify:

```js
    message: "Unexpected character '`'",
    stack: "Error at new JS_Parse_Error (eval at <anonymous>
    (.../node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0)...
```

The line where apparently contains the error its 39 on `ltx/lib/escape.js`:

```js
    ...
    throw new Error(`Illegal XML character 0x${num.toString(16)}`)
    ...
```

The use of es6 string template  in the latest changes.

Hope you can help me. For now i downgrade ltx to 2.7.1 and works perfectly.

Thanks

**Comment by sonnyp** [comment]
thanks

fixed in 2.7.3
