### ISSUE TITLE
`ltx.stringify` should escape XML specific chars correctly

### ISSUE THREAD

**Issue by aprilandjan** [xmppjs/ltx#139]
The raw xml string:

```xml
<a>
  &gt;a
</a>
```

Turn it into parsed result object:

```
const result = ltx.parse(rawXml);
```

when use `ltx.stringify(result)` against the parsed result object, it gives out the following incorrect output:

```xml
<a>
  >a
<a>
```

I checked the source codes and the unit tests, it seems that the `result.toString()` gives out the correct string because it do escape, but `ltx.stringify` does not.

**Comment by sonnyp** [comment]
You are absolutely right. Want to give it a try? Should be fairly easy if you look at what `toString` does.

**Comment by aprilandjan** [comment]
@sonnyp glad I can help with that. I've submit a PR, please have a look :)
